### ISSUE TITLE
Lags

### ISSUE THREAD

**Issue by PoweredByAndrox** [babbaj/nether-pathfinder#19]
DId you run your mod to test it?
Ok, i did it and my game deep into lags (where 2fps) i think it's because your FAST algorithm make it's laggy. Fix this please. Also i can't use it in chat, when i try to type something about mod it is crash with log:

[crash-2024-03-11_18.54.14-client.txt](https://github.com/babbaj/nether-pathfinder/files/14562028/crash-2024-03-11_18.54.14-client.txt)
[2024-03-11-7.log.gz](https://github.com/babbaj/nether-pathfinder/files/14562030/2024-03-11-7.log.gz)

Laggometr:
![image](https://github.com/babbaj/nether-pathfinder/assets/38520826/2029243d-effe-405c-bf37-cc6a9216bb83)

**Comment by 0-x-2-2** [comment]
You compiled the mod incorrectly or something and you are in the overworld? You also did not provide any relevant info.

This is entirely user error:
```
java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getMinecraft()Lnet/minecraft/client/Minecraft;
	at com.babbaj.pathfinder.ExamplePathfinderControl.addToChatHistory(ExamplePathfinderControl.java:130)
	at com.babbaj.pathfinder.ExamplePathfinderControl.onChat(ExamplePathfinderControl.java:404)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_14_ExamplePathfinderControl_onChat_ClientChatEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onClientSendMessage(ForgeEventFactory.java:436)
```

**Comment by PoweredByAndrox** [comment]
I put mod into mods folder of 1.12.2 forge. How i can use in other worlds? I need only render path with path finder, wanna use it like nativation... But the mod use dll with it's own PathFinding algorithm that in C++ language, i need on Java like in Minecraft. How i can achive it?
